import type { DayForecast, WeatherCondition, HourlyForecast } from '@/types';

const conditions: Record<WeatherCondition, string> = {
  'sunny': 'Açık Güneşli',
  'partly-cloudy': 'Parçalı Bulutlu',
  'cloudy': 'Bulutlu',
  'rainy': 'Yağmurlu',
  'stormy': 'Fırtınalı',
  'snowy': 'Karlı',
  'foggy': 'Sisli',
};

function makeHourly(baseTemp: number, cond: WeatherCondition): HourlyForecast[] {
  const hours = ['06:00', '09:00', '12:00', '15:00', '18:00', '21:00'];
  const offsets = [-3, -1, 2, 3, 1, -2];
  const conds: WeatherCondition[] = ['cloudy', 'partly-cloudy', cond, cond, 'partly-cloudy', 'cloudy'];
  return hours.map((hour, i) => ({
    hour,
    temp: baseTemp + offsets[i],
    condition: conds[i],
    precipitation: cond === 'rainy' || cond === 'stormy' ? (i >= 2 && i <= 3 ? 80 : 20) : cond === 'snowy' ? 60 : 0,
  }));
}

export const weekForecast: DayForecast[] = [
  {
    id: 'day1',
    dayName: 'Pazartesi',
    date: '1 Eki 2026',
    condition: 'sunny',
    conditionLabel: conditions['sunny'],
    high: 28, low: 16, temp: 24,
    humidity: 35, windSpeed: 12, windDirection: 'Kuzey',
    precipitation: 0, uvIndex: 8, visibility: 15, pressure: 1018,
    sunrise: '06:45', sunset: '18:52',
    feelsLike: 26,
    hourly: makeHourly(24, 'sunny'),
  },
  {
    id: 'day2',
    dayName: 'Salı',
    date: '2 Eki 2026',
    condition: 'partly-cloudy',
    conditionLabel: conditions['partly-cloudy'],
    high: 26, low: 15, temp: 22,
    humidity: 48, windSpeed: 16, windDirection: 'Kuzeydoğu',
    precipitation: 10, uvIndex: 6, visibility: 12, pressure: 1015,
    sunrise: '06:46', sunset: '18:50',
    feelsLike: 23,
    hourly: makeHourly(22, 'partly-cloudy'),
  },
  {
    id: 'day3',
    dayName: 'Çarşamba',
    date: '3 Eki 2026',
    condition: 'rainy',
    conditionLabel: conditions['rainy'],
    high: 21, low: 13, temp: 18,
    humidity: 78, windSpeed: 22, windDirection: 'Doğu',
    precipitation: 85, uvIndex: 2, visibility: 6, pressure: 1008,
    sunrise: '06:47', sunset: '18:48',
    feelsLike: 16,
    hourly: makeHourly(18, 'rainy'),
  },
  {
    id: 'day4',
    dayName: 'Perşembe',
    date: '4 Eki 2026',
    condition: 'stormy',
    conditionLabel: conditions['stormy'],
    high: 19, low: 12, temp: 15,
    humidity: 88, windSpeed: 38, windDirection: 'Güneydoğu',
    precipitation: 95, uvIndex: 1, visibility: 4, pressure: 998,
    sunrise: '06:48', sunset: '18:46',
    feelsLike: 12,
    hourly: makeHourly(15, 'stormy'),
  },
  {
    id: 'day5',
    dayName: 'Cuma',
    date: '5 Eki 2026',
    condition: 'cloudy',
    conditionLabel: conditions['cloudy'],
    high: 22, low: 14, temp: 19,
    humidity: 62, windSpeed: 18, windDirection: 'Batı',
    precipitation: 30, uvIndex: 3, visibility: 9, pressure: 1011,
    sunrise: '06:49', sunset: '18:44',
    feelsLike: 19,
    hourly: makeHourly(19, 'cloudy'),
  },
  {
    id: 'day6',
    dayName: 'Cumartesi',
    date: '6 Eki 2026',
    condition: 'foggy',
    conditionLabel: conditions['foggy'],
    high: 20, low: 11, temp: 16,
    humidity: 92, windSpeed: 8, windDirection: 'Kuzeybatı',
    precipitation: 15, uvIndex: 2, visibility: 2, pressure: 1014,
    sunrise: '06:50', sunset: '18:42',
    feelsLike: 15,
    hourly: makeHourly(16, 'foggy'),
  },
  {
    id: 'day7',
    dayName: 'Pazar',
    date: '7 Eki 2026',
    condition: 'snowy',
    conditionLabel: conditions['snowy'],
    high: 5, low: -2, temp: 2,
    humidity: 85, windSpeed: 25, windDirection: 'Kuzey',
    precipitation: 70, uvIndex: 1, visibility: 3, pressure: 1020,
    sunrise: '06:51', sunset: '18:40',
    feelsLike: -3,
    hourly: makeHourly(2, 'snowy'),
  },
];
